// Auto-generated by deploy script — DO NOT EDIT MANUALLY
export const LENDING_ADDRESSES = {
  Stablecoin:  "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  MockWETH:    "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
  LendingPool: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
};

export const NETWORK_CONFIG = {
  chainId:   "1337",
  chainName: "Localhost 8545",
  rpcUrl:    "http://127.0.0.1:8545",
};
